

DROP TABLE IF EXISTS vacas.temp_geonames;
DROP TABLE IF EXISTS vacas.temp_country_codes;
DROP TABLE IF EXISTS vacas.temp_level_1a;
DROP TABLE IF EXISTS vacas.temp_locations;
DROP TABLE IF EXISTS vacas.temp_projects;
DROP TABLE IF EXISTS vacas.temp_transaction;

DROP TABLE IF EXISTS vacas.TRANSACTION;
DROP TABLE IF EXISTS vacas.CURRENCY;
DROP TABLE IF EXISTS vacas.LEVEL_1A;
DROP TABLE IF EXISTS vacas.PROJECT;
DROP TABLE IF EXISTS vacas.TYPE_STATUS;
DROP TABLE IF EXISTS vacas.COUNTRY_CODE;
DROP TABLE IF EXISTS vacas.GEONAME;
DROP TABLE IF EXISTS vacas.LOCATION;